image: python:3.9-slim

stages:
  - test
  - deploy

variables:
  MYSQL_ROOT_PASSWORD: root_password

services:
  - name: mysql:5.7
    alias: users_db
    command: ["mysqld", "--port=3307"]
    variables:
      MYSQL_DATABASE: users_db
      MYSQL_ROOT_PASSWORD: root_password

  - name: mysql:5.7
    alias: auth_db
    command: ["mysqld", "--port=3308"]
    variables:
      MYSQL_DATABASE: auth_db
      MYSQL_ROOT_PASSWORD: root_password

.before_script_template: &before_script_definition
  before_script:
    - echo "Starting setup..."
    # Install dependencies with sudo
    - sudo apt-get update
    - sudo apt-get install -y default-libmysqlclient-dev build-essential netcat-openbsd python3 python3-pip mysql-client
    # Debug MySQL
    - echo "Testing MySQL connections..."
    - mysqladmin -h 127.0.0.1 -P 3307 -u root -proot_password ping || true
    - mysqladmin -h 127.0.0.1 -P 3308 -u root -proot_password ping || true
    # Install Python requirements
    - sudo python3 -m pip install --upgrade pip
    - sudo python3 -m pip install -r backend/requirements.txt
    - sudo python3 -m pip install pytest pytest-cov
    # Wait for MySQL services with verbose output
    - |
      echo "Waiting for MySQL services..."
      for i in {1..30}; do
        echo "Attempt $i: Checking MySQL connections..."
        if nc -zv 127.0.0.1 3307 && nc -zv 127.0.0.1 3308; then
          echo "MySQL services are up!"
          break
        fi
        echo "Services not ready. Waiting..."
        sleep 2
      done

test_app:
  stage: test
  tags:
    - shell
  variables:
    SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root_password@127.0.0.1:3307/users_db"
    SQLALCHEMY_BINDS: '{"users_db":"mysql+pymysql://root:root_password@127.0.0.1:3307/users_db","auth_db":"mysql+pymysql://root:root_password@127.0.0.1:3308/auth_db"}'
    SECRET_KEY: "test-key"
  <<: *before_script_definition
  script:
    - echo "Running tests..."
    - python3 -m pytest backend/tests/ -v

coverage:
  stage: test
  tags:
    - shell
  variables:
    SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root_password@127.0.0.1:3307/users_db"
    SQLALCHEMY_BINDS: '{"users_db":"mysql+pymysql://root:root_password@127.0.0.1:3307/users_db","auth_db":"mysql+pymysql://root:root_password@127.0.0.1:3308/auth_db"}'
    SECRET_KEY: "test-key"
  <<: *before_script_definition
  script:
    - echo "Running coverage tests..."
    - python3 -m pytest backend/tests/ --cov=app --cov-report=term-missing
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - cd backend
    - docker-compose -f docker-compose.yml down --remove-orphans
    - docker-compose -f docker-compose.yml up -d --build
  when: manual
