image: python:3.7-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  MYSQL_ROOT_PASSWORD: "root_password"

cache:
  paths:
    - .pip-cache
    - venv/

stages:
  - test

services:
  - mysql:5.7

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r backend/requirements.txt
  - pip install pytest pytest-cov

test_models:
  stage: test
  variables:
    SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root_password@mysql/test_users_db"
    SQLALCHEMY_BINDS: '{"users_db":"mysql+pymysql://root:root_password@mysql/test_users_db","auth_db":"mysql+pymysql://root:root_password@mysql/test_auth_db"}'
    SECRET_KEY: "test-key"
  script:
    - pytest backend/tests/test_models.py -v

test_user_service:
  stage: test
  variables:
    SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root_password@mysql/test_users_db"
    SQLALCHEMY_BINDS: '{"users_db":"mysql+pymysql://root:root_password@mysql/test_users_db","auth_db":"mysql+pymysql://root:root_password@mysql/test_auth_db"}'
    SECRET_KEY: "test-key"
  script:
    - pytest backend/tests/test_user_service.py -v

test_routes:
  stage: test
  variables:
    SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root_password@mysql/test_users_db"
    SQLALCHEMY_BINDS: '{"users_db":"mysql+pymysql://root:root_password@mysql/test_users_db","auth_db":"mysql+pymysql://root:root_password@mysql/test_auth_db"}'
    SECRET_KEY: "test-key"
  script:
    - pytest backend/tests/test_routes.py -v

coverage:
  stage: test
  variables:
    SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root_password@mysql/test_users_db"
    SQLALCHEMY_BINDS: '{"users_db":"mysql+pymysql://root:root_password@mysql/test_users_db","auth_db":"mysql+pymysql://root:root_password@mysql/test_auth_db"}'
    SECRET_KEY: "test-key"
  script:
    - pytest backend/tests/ --cov=app --cov-report=term-missing --cov-report=xml
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
