image: python:3.7-slim

variables:
  MYSQL_ROOT_PASSWORD: root_password

services:
  - name: mysql:5.7
    alias: users_db
    variables:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: users_db

  - name: mysql:5.7
    alias: auth_db
    variables:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auth_db

stages:
  - test
  - deploy

test_app:
  stage: test
  variables:
    SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root_password@users_db:3306/users_db"
    SQLALCHEMY_BINDS: '{"users_db":"mysql+pymysql://root:root_password@users_db:3306/users_db","auth_db":"mysql+pymysql://root:root_password@auth_db:3306/auth_db"}'
    SECRET_KEY: "test-key"
  before_script:
    - apt-get update
    - apt-get install -y default-libmysqlclient-dev build-essential netcat-openbsd
    - pip install -r backend/requirements.txt
    - pip install pytest pytest-cov
    # Wait for users_db
    - |
      echo "Waiting for users_db..."
      while ! nc -z users_db 3306; do
        sleep 1
      done
      echo "users_db is up"
    # Wait for auth_db
    - |
      echo "Waiting for auth_db..."
      while ! nc -z auth_db 3306; do
        sleep 1
      done
      echo "auth_db is up"
  script:
    - python -m pytest backend/tests/ -v

coverage:
  stage: test
  variables:
    SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root_password@users_db:3306/users_db"
    SQLALCHEMY_BINDS: '{"users_db":"mysql+pymysql://root:root_password@users_db:3306/users_db","auth_db":"mysql+pymysql://root:root_password@auth_db:3306/auth_db"}'
    SECRET_KEY: "test-key"
  before_script:
    - apt-get update
    - apt-get install -y default-libmysqlclient-dev build-essential netcat-openbsd
    - pip install -r backend/requirements.txt
    - pip install pytest pytest-cov
    # Wait for users_db
    - |
      echo "Waiting for users_db..."
      while ! nc -z users_db 3306; do
        sleep 1
      done
      echo "users_db is up"
    # Wait for auth_db
    - |
      echo "Waiting for auth_db..."
      while ! nc -z auth_db 3306; do
        sleep 1
      done
      echo "auth_db is up"
  script:
    - python -m pytest backend/tests/ --cov=app --cov-report=term-missing
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - cd backend
    - docker-compose -f docker-compose.yml down --remove-orphans
    - docker-compose -f docker-compose.yml up -d --build
  when: manual
