image: python:3.7-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  MYSQL_ROOT_PASSWORD: "root_password"

cache:
  paths:
    - .pip-cache
    - venv/

stages:
  - setup
  - test

services:
  - mysql:5.7

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r backend/requirements.txt
  - pip install pytest pytest-cov
  - until mysqladmin ping -h mysql --silent; do echo "Waiting for MySQL..."; sleep 2; done

setup_database:
  stage: setup
  script:
    - mysql -h mysql -u root -proot_password -e "CREATE DATABASE IF NOT EXISTS test_users_db;"
    - mysql -h mysql -u root -proot_password -e "CREATE DATABASE IF NOT EXISTS test_auth_db;"

test_models:
  stage: test
  script:
    - pytest backend/tests/test_models.py -v

test_user_service:
  stage: test
  script:
    - pytest backend/tests/test_user_service.py -v

test_routes:
  stage: test
  script:
    - pytest backend/tests/test_routes.py -v

coverage:
  stage: test
  script:
    - pytest backend/tests/ --cov=app --cov-report=term-missing --cov-report=xml
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
